Repository jingni1115/Catcher, pull requests merged in 2023-10, with the labels that each got.

#14 [FEAT] : ⚙️ 회원관리와 데이터 관리(CRUD)를 위한 FirebaseManager, DBManager 생성
  .gitignore
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/GoogleService-Info.plist
  Catcher/Catcher/Util/Managers/DBManager.swift
  Catcher/Catcher/Util/Managers/DBProtocol.swift
  Catcher/Catcher/Util/Managers/FireStorageManager.swift
  Catcher/Catcher/Util/Managers/FirebaseErrors.swift
  Catcher/Catcher/Util/Managers/FirebaseManager.swift
  Catcher/Catcher/Util/Managers/LocalFileManager.swift
  Catcher/Catcher/Util/Managers/UserDefaultsManager.swift
  Catcher/Catcher/Util/Managers/UserInfo.swift
Labels: feature, feedback

#15 [FIX] : 🔧 DB 변경에 따른 데이터 모델 수정
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Util/Extensions/Array+.swift
  Catcher/Catcher/Util/Managers/DBManager.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/UserInfo.swift
Labels: fix, feedback

#17 [FEAT] : ⚙️ 메인 페이지에 요청한 데이터 보여주기 구현
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Configure/ThemeColor.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/DefaultSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/HomeItem.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainItems.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/SectionHeaderView.swift
  Catcher/Catcher/Util/Managers/DBProtocol.swift
  Catcher/Catcher/Util/Managers/FireStorageManager.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/ImageCacheManager.swift
  Catcher/Catcher/Util/Managers/UserInfo.swift
Labels: feature, feedback

#18 [FEAT] : ⚙️ 설문페이지 UI
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Scenes/TabBar/SurveyViewController.swift
Labels: design

#19 [FEAT] : ⚙️ UserInfoVC 완성
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Configure/AppConstraint.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/DefaultSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/HomeItem.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Util/Extensions/String+.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
Labels: feature, design

#20 MainPage UI 변경에 따른 오류 해결
  .gitignore
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher.xcodeproj/project.xcworkspace/xcuserdata/gimjieun.xcuserdatad/UserInterfaceState.xcuserstate
  Catcher/Catcher.xcodeproj/xcuserdata/gimjieun.xcuserdatad/xcschemes/xcschememanagement.plist
  Catcher/Catcher/Configure/AppConstraint.swift
  Catcher/Catcher/Info.plist
  Catcher/Catcher/Scenes/TabBar/MainPage/DefaultSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/Dummy.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainItems.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Util/Extensions/Array+.swift
  Catcher/Catcher/Util/Extensions/UIImage+.swift
  Catcher/Catcher/Util/Managers/DatabaseManager.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/StorageManager.swift
Labels: fix, feedback

#23 [FIX] : 🐛 MainPage Section 숨김 처리에 대한 오류 해결
  Catcher/Catcher/Scenes/TabBar/MainPage/DefaultSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/Dummy.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/SectionHeaderView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewModel.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/UserInfo.swift
Labels: feature, fix, design

#26 [FEAT] : ⚙️ 회원가입 기능 추가
  Catcher/Catcher/LoginPage/LoginView.swift
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/LoginPage/RegisterView.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.xib
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
Labels: feature

#30 [DESIGN] : 🎨 MainPage UI 변경
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Configure/AppConstraint.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/DefaultSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewModel.swift
  Catcher/Catcher/Util/StrokeLabel.swift
Labels: design, feedback

#35 [DESIGN] : 🎨 UserInfoView UI 변경
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewModel.swift
  Catcher/Catcher/Util/Extensions/NSAttributedString+.swift
  Catcher/Catcher/Util/Extensions/String+.swift
Labels: design, feedback
