Repository jingni1115/Catcher, pull requests merged in 2023-11, with the labels that each got.

#42 CoreML을 사용한 이미지 변환 기능 추가
  .gitignore
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Configure/ThemeColor.swift
  Catcher/Catcher/Info.plist
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.xib
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewModel.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/ImageCacheManager.swift
  Catcher/Catcher/ko.lproj/LaunchScreen.strings
  Catcher/Catcher/ko.lproj/Main.strings
Labels: feature

#43 [DESIGN] : 🎨 앱 아이콘 추가
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/100.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/1024.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/114.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/120.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/144.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/152.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/167.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/180.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/20.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/29.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/40.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/50.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/57.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/58.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/60.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/72.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/76.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/80.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/87.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: design

#47 [FEAT] : ⚙️ 채팅 차단 기능 추가
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/Scenes/IntroViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewModel.swift
  Catcher/Catcher/Util/Managers/FireStorageManager.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/FirebaseManager.swift
  Catcher/Catcher/Util/Managers/NotificationManager.swift
  Catcher/Catcher/Util/Managers/UserInfo.swift
Labels: feature, feedback

#51 [FEAT] : ⚙️ 1:1 문의하기 기능 추가
  Catcher/Catcher/Assets.xcassets/sample1.imageset/Contents.json
  Catcher/Catcher/Assets.xcassets/sample1.imageset/sample4.jpg
  Catcher/Catcher/Assets.xcassets/sample2.imageset/Contents.json
  Catcher/Catcher/Assets.xcassets/sample2.imageset/sample6.jpg
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/AskPage/AskViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ReportPage/ReportViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewController/RevokeViewController.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
Labels: feature

#52 [FEAT] : ⚙️ 회원가입페이지 스크롤뷰 추가
  Catcher/Catcher/LoginPage/LoginView.swift
  Catcher/Catcher/LoginPage/RegisterView.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
Labels: feature

#53 [FEAT] : ⚙️ setKeyboardObserver 추가
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Util/Extensions/UIViewController+.swift
Labels: feature

#67 [FIX] : 🔧 잔잔바리 수정
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/LoginPage/RegisterView.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewModel/ProfileSettingViewModel.swift
  Catcher/Catcher/Util/Managers/FireStorageManager.swift
Labels: fix

#70 [FIX] : 🔧 MypageVC 정보 임시 수정
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
Labels: fix

#71 [FIX] : 🔧 잔잔바리 수정
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.xib
Labels: design

#73 [FIX] : 🔧 FireStoreManager UID 수정
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
Labels: fix

#74 [DEPLOY] : 🚀 배포 전 이슈 해결
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewController/RevokeViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewModel/RevokeViewModel.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
Labels: fix

#75 [FEAT] : ⚙️ MainPage 찜 개수로 랭킹 변경
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewModel.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Models/UserInfo.swift
Labels: feature

#76 [FEAT] : ⚙️ 프로필 수정 기능 추가, 닉네임 글자수 제한 추가
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
Labels: feature, fix

#78 [DESIGN] : 🎨 MainPage Rank Section Cell UI 변경
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
Labels: design

#82 Feat/chat
  Catcher/Catcher/Scenes/TabBar/ChatPage/ConversationTableViewCell.swift
  Catcher/Catcher/Scenes/TabBar/ViewModel/RevokeViewModel.swift
  Catcher/Catcher/Util/Managers/DatabaseManager.swift
  Catcher/Catcher/Util/Models/ConversationsModels.swift
Labels: feature, fix

#83 [DESIGN] : 🎨 UserInfoVC UI 변경
  Catcher/Catcher/Configure/ThemeColor.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Util/Extensions/Date+.swift
Labels: design

#85 [DESIGN] : 🎨 UserInfoVC UI 수정
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
Labels: fix, design

#86 [FIX] : 🔧 UserInfo 데이터 모델 수정
  Catcher/Catcher/Scenes/TabBar/MainPage/Dummy.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewModel/ProfileSettingViewModel.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Models/UserInfo.swift
Labels: fix

#88 [FEAT] : ⚙️ 이미지 변환, 저장을 자유롭게 할 수 있는 ImageFactoryVC 추가
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Scenes/TabBar/MainPage/DefaultSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/RankSectionCell.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/ProfileSettingViewController.xib
Labels: feature

#89 [FIX] : 🔧 마이페이지 나이 -> 찜 받은 개수로 변경
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
Labels: fix

#90 [DESIGN] : 🎨 AppIcon, Logo 변경
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/100.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/1024.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/114.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/120.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/144.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/152.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/167.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/180.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/20.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/29.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/40.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/50.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/57.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/58.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/60.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/72.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/76.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/80.png
  Catcher/Catcher/Assets.xcassets/AppIcon.appiconset/87.png
  Catcher/Catcher/Assets.xcassets/Catcher.imageset/Catcher 1.png
  Catcher/Catcher/Assets.xcassets/Catcher.imageset/Catcher 2.png
  Catcher/Catcher/Assets.xcassets/Catcher.imageset/Catcher.png
  Catcher/Catcher/Assets.xcassets/Icon.imageset/Contents.json
  Catcher/Catcher/Assets.xcassets/Icon.imageset/Icon 1.png
  Catcher/Catcher/Assets.xcassets/Icon.imageset/Icon 2.png
  Catcher/Catcher/Assets.xcassets/Icon.imageset/Icon.png
  Catcher/Catcher/Assets.xcassets/appleid_button.imageset/Contents.json
  Catcher/Catcher/Assets.xcassets/appleid_button.imageset/appleid_button@2x.png
  Catcher/Catcher/Base.lproj/LaunchScreen.storyboard
  Catcher/Catcher/Scenes/IntroViewController.xib
Labels: design

#92 [FEAT] : ⚙️ 유저 차단 후 다시 보지 않기 기능 구현
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ReportPage/ReportViewController.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/NotificationManager.swift
Labels: feature

#98 배포 관련 수정 및 버그 픽스
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Scenes/TabBar/MainPage/Model/Dummy.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/Model/HomeItem.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/Model/MainItems.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/View/MainPageView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/View/SectionHeaderView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/View/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/ViewModel/MainPageViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/ViewModel/UserInfoViewModel.swift
  Catcher/Catcher/Util/Managers/FireStorageManager.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
Labels: fix

#99 Fix/deploy
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/AppDelegate.swift
  Catcher/Catcher/LoginPage/LoginView.swift
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChatViewController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChattingDetailViewController.swift
Labels: fix

#101 Fix/deploy
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChatViewController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChattingDetailViewController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/PhotoViewerViewController.swift
Labels: fix

#102 [FEAT] : ⚙️ Button Debounce를 위한 메서드 추가
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Info.plist
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewController/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewController/ProfileSettingViewController.xib
  Catcher/Catcher/Util/Extensions/UIButton+.swift
Labels: feature, feedback

#103 Fix/deploy 채팅 스크롤 올라가는 문제 해결
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChattingDetailViewController.swift
Labels: fix

#104 Debounce 적용, README 꾸미기
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ReportPage/ReportViewController.swift
  README.md
Labels: feature, feedback

#105 [FIX] : 🔧 회원가입 비밀번호 에러 문구 수정, 에러 메세지 잘리는 문제 해결
  Catcher/Catcher/LoginPage/RegisterView.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
Labels: fix

#107 Button title font 통일 및 Debounce 적용
  Catcher/Catcher/LoginPage/LoginView.swift
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/LoginPage/RegisterView.swift
  Catcher/Catcher/LoginPage/ResetPWViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/AskPage/AskViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ReportPage/ReportViewController.swift
  Catcher/Catcher/Scenes/TabBar/ViewController/ProfileSettingViewController.swift
Labels: fix

#111 [FIX] : 🐛 예상치 못하게 일어나는 앱 크래시 방지
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/LoginPage/LoginView.swift
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewController.xib
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewModel.swift
  Catcher/Catcher/Util/CheckDevice.swift
  Catcher/Catcher/Util/Extensions/UIImage+.swift
  Catcher/Catcher/Util/Managers/FireStoreManager.swift
  Catcher/Catcher/Util/Managers/UserDefaultsManager.swift
Labels: fix

#112 README 수정
  README.md
Labels: fix

#114 업데이트를 위한 수정
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Factory/AlertFactory.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/View/UserInfoView.swift
  Catcher/Catcher/Util/Extensions/UIButton+.swift
Labels: fix

#115 [DOCS] : 📚 로그인, 회원가입, 마이페이지 주석 추가 및 불필요 코드 삭제
  Catcher/Catcher/LoginPage/LoginView.swift
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/LoginPage/RegisterView.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/LoginPage/ResetPWViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/AppVersion/AppVersionView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/AskPage/AskViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MenuTableViewCell.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ReportPage/ReportViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/Revoke/RevokeView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/Revoke/RevokeViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/Revoke/RevokeViewModel.swift
Labels: fix

#116 [DOCS]: 파일 삭제 및 주석 처리 진행
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/LoginPage/CustomTextField/CustomTextField.swift
  Catcher/Catcher/LoginPage/CustomTextField/CustomTextField.xib
  Catcher/Catcher/Scenes/Base/BaseTabBarController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChatViewController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChattingDetailViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Util/Common.swift
  Catcher/Catcher/Util/CommonUtil.swift
  Catcher/Catcher/Util/Managers/DatabaseManager.swift
  Catcher/Catcher/Util/Managers/LocalFileManager.swift
  Catcher/Catcher/Util/Managers/StorageManager.swift
Labels: fix

#117 [DEPLOY] : 🚀 배포를 위한 커밋
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/Factory/AlertFactory.swift
  Catcher/Catcher/LoginPage/CustomTextField/CustomTextField.swift
  Catcher/Catcher/LoginPage/CustomTextField/CustomTextField.xib
  Catcher/Catcher/LoginPage/LoginView.swift
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/LoginPage/RegisterView.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/LoginPage/ResetPWViewController.swift
  Catcher/Catcher/Scenes/Base/BaseTabBarController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChatViewController.swift
  Catcher/Catcher/Scenes/TabBar/ChatPage/ChattingDetailViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/View/UserInfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/AppVersion/AppVersionView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/AskPage/AskViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ImageFactory/ImageFactoryViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MenuTableViewCell.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewModel.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ReportPage/ReportViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/Revoke/RevokeView.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/Revoke/RevokeViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/Revoke/RevokeViewModel.swift
  Catcher/Catcher/Util/Common.swift
  Catcher/Catcher/Util/CommonUtil.swift
  Catcher/Catcher/Util/Extensions/UIButton+.swift
  Catcher/Catcher/Util/Managers/DatabaseManager.swift
  Catcher/Catcher/Util/Managers/LocalFileManager.swift
  Catcher/Catcher/Util/Managers/StorageManager.swift
Labels: notice

#120 배포를 위한 수정
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/LoginPage/RegisterViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/MyPageViewController.swift
Labels: fix

#122 이슈 해결 및 Read.me 수정
  Catcher/Catcher.xcodeproj/project.pbxproj
  Catcher/Catcher/LoginPage/LoginViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/MainPageViewController.swift
  Catcher/Catcher/Scenes/TabBar/MainPage/UserInfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/InfoPage/InfoViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ProfileSetting/ProfileSettingViewController.swift
  Catcher/Catcher/Scenes/TabBar/MyPage/ReportPage/ReportViewController.swift
  Catcher/Catcher/Util/Extensions/UIButton+.swift
  README.md
Labels: fix
